In [1]:
import numpy as np

def sigmoid(x):
    return 1 / (1+ np.exp(-x))

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias

    def feed_forward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return sigmoid(total)

weights = np.array([0.5, -0.5])
bias = 0.0

In [3]:
import numpy as np

def sigmoid(x):
    return 1 / (1+ np.exp(-x))

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias

    def feed_forward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        print(total)
        return sigmoid(total)

weights = np.array([0.5, -0.5])
bias = 0.0

neuron = Neuron(weights, bias)

inputs = np.array([1,2])

output = neuron.feed_forward(inputs)
print("Neurono atsakymas: ", output)

-0.5
Neurono atsakymas:  0.3775406687981454


In [7]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1-x)
class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1], 4)
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np.zeros(y.shape)

    def feed_forward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.output = sigmoid(np.dot(self.layer1, self.weights2))

    def backdrop(self):
        # gradientinis nuokrypis
        d_weights2 = np.dot(self.layer1.T, (2*(self.y - self.output) * sigmoid_derivative(self.output)))
        d_weights1 = np.dot(self.input.T, (np.dot(2*(self.y - self.output) * sigmoid_derivative(self.output), self.weights2.T) * sigmoid_derivative(self.layer1)))
        # atnaujinam svorius
        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, iterations):
        for _ in range(iterations):
            self.feed_forward()
            self.backdrop()
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])
targets = np.array([[0], [1], [1], [0]])

nn = NeuralNetwork(inputs, targets)
nn.train(100000)

print(nn.output)

[[0.00636006]
 [0.99581003]
 [0.99625871]
 [0.0012369 ]]


In [20]:
import numpy as np 
from sklearn.datasets import load_iris 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing  import StandardScaler

def sigmoid(x):
    return  1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1-x)

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.weights_input_hidden =  np.random.rand(input_size, hidden_size)
        self.weights_output_hidden = np.random.rand(hidden_size, output_size)
    
    def feed_forward(self, X):
        self.hidden_layer = sigmoid(np.dot(X, self.weights_input_hidden))
        self.output = sigmoid(np.dot(self.hidden_layer, self.weights_output_hidden))
    
    def backpropagation(self, X, y, learning_rate):
        output_error = y - self.output
        d_output = output_error * sigmoid_derivative(self.output)
        hidden_error = d_output.dot(self.weights_output_hidden.T)
        d_hidden = hidden_error * sigmoid_derivative(self.hidden_layer)
        self.weights_output_hidden += self.hidden_layer.T.dot(d_output) * learning_rate
        self.weights_input_hidden += X.T.dot(d_hidden) * learning_rate
    
    def train(self, X, y, epochs, learning_rate):
        for _ in range(epochs):
            self.feed_forward(X)
            self.backpropagation(X, y, learning_rate)
    
    def predict(self, X):
        self.feed_forward(X)
        return np.round(self.output)

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

input_size = X_train_scaled.shape[1]
output_size = len(np.unique(y_train))
# to do
hidden_size = 8

nn =  NeuralNetwork(input_size, hidden_size, output_size)

nn.train(X_train_scaled, np.eye(output_size)[y_train], epochs=5000, learning_rate=0.1)

y_pred =  nn.predict(X_test_scaled)

# print(y_pred)

accuracy = np.mean(y_pred == np.eye(output_size)[y_test])
print(accuracy)

1.0


In [11]:
np.eye(output_size)[y_train]

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1

In [25]:
import numpy as np 
from sklearn.datasets import load_iris, load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing  import StandardScaler

def sigmoid(x):
    return  1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1-x)

class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        self.weights_input_hidden =  np.random.rand(input_size, hidden_size)
        self.weights_output_hidden = np.random.rand(hidden_size, output_size)
    
    def feed_forward(self, X):
        self.hidden_layer = sigmoid(np.dot(X, self.weights_input_hidden))
        self.output = sigmoid(np.dot(self.hidden_layer, self.weights_output_hidden))
    
    def backpropagation(self, X, y, learning_rate):
        output_error = y - self.output
        d_output = output_error * sigmoid_derivative(self.output)
        hidden_error = d_output.dot(self.weights_output_hidden.T)
        d_hidden = hidden_error * sigmoid_derivative(self.hidden_layer)
        self.weights_output_hidden += self.hidden_layer.T.dot(d_output) * learning_rate
        self.weights_input_hidden += X.T.dot(d_hidden) * learning_rate
    
    def train(self, X, y, epochs, learning_rate):
        for _ in range(epochs):
            self.feed_forward(X)
            self.backpropagation(X, y, learning_rate)
    
    def predict(self, X):
        self.feed_forward(X)
        return np.round(self.output)

wines = load_wine()
X = wines.data
y = wines.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

input_size = X_train_scaled.shape[1]
output_size = len(np.unique(y_train))

hidden_size = 8

nn =  NeuralNetwork(input_size, hidden_size, output_size)

nn.train(X_train_scaled, np.eye(output_size)[y_train], epochs=5000, learning_rate=0.1)

y_pred =  nn.predict(X_test_scaled)

print(y_pred)

accuracy = np.mean(y_pred == np.eye(output_size)[y_test])
print(accuracy)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
1.0
